Build-qt.sh: Add -headerpad_max_install_names to OpenSSL linkage
This addresses errors like the following where updating install names
or rpaths fails  due to insufficient header padding:

```
+ install_name_tool -id /path/to/qt-everywhere-deps-5.15.18/openssl-1.1.1w/libcrypto.dylib /path/to/qt-everywhere-deps-5.15.18/openssl-1.1.1w/libcrypto.dylib
+ install_name_tool -change /usr/local/ssl/lib/libcrypto.1.0.0.dylib /path/to/qt-everywhere-deps-5.15.18/openssl-1.1.1w/libcrypto.dylib -id /path/to/qt-everywhere-deps-5.15.18/openssl-1.1.1w/libssl.dylib /path/to/qt-everywhere-deps-5.15.18/openssl-1.1.1w/libssl.dylib
error: /Applications/Xcode-26.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /path/to/qt-everywhere-deps-5.15.18/openssl-1.1.1w/libssl.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)
```